"""E2E smoke pipeline: load config, solve ODE, and export figure/results."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import solve_ivp

from rna_llps.config import load_params
from rna_llps.models.minimal_ode import rhs_minimal_system


@dataclass(frozen=True)
class SmokeArtifacts:
    """Paths generated by one smoke run."""

    npz_path: Path
    figure_path: Path
    summary_path: Path


def run_smoke(
    config_path: str | Path,
    output_dir: str | Path,
    figure_dir: str | Path,
    t_end: float = 40.0,
) -> SmokeArtifacts:
    """Run end-to-end smoke simulation.

    Args:
        config_path: YAML parameters.
        output_dir: Directory for numerical artifacts.
        figure_dir: Directory for figure artifacts.
        t_end: End time for integration.

    Returns:
        Paths to generated artifacts.
    """
    params = load_params(config_path)
    output_path = Path(output_dir)
    figure_path = Path(figure_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    figure_path.mkdir(parents=True, exist_ok=True)

    y0 = np.array([0.2, 0.1, 0.05, 0.05], dtype=float)
    t_eval = np.linspace(0.0, t_end, 300)

    atol = np.array([1e-10, 1e-10, 1e-12, 1e-12], dtype=float)
    solution = solve_ivp(
        fun=lambda t, y: rhs_minimal_system(t, y, params),
        t_span=(0.0, t_end),
        y0=y0,
        method="Radau",
        t_eval=t_eval,
        rtol=1e-8,
        atol=atol,
    )

    if not solution.success:
        msg = f"Smoke ODE solve failed: {solution.message}"
        raise RuntimeError(msg)

    npz_file = output_path / "smoke_timeseries.npz"
    np.savez_compressed(npz_file, t=solution.t, y=solution.y)

    fig, ax = plt.subplots(figsize=(6, 4))
    labels = ["R", "P", "x_bar", "y_bar"]
    for idx, label in enumerate(labels):
        ax.plot(solution.t, solution.y[idx], label=label)
    ax.set_xlabel("t")
    ax.set_ylabel("state")
    ax.set_title("RNA LLPS minimal smoke trajectory")
    ax.legend()
    ax.grid(alpha=0.3)

    fig_file = figure_path / "smoke_trajectory.png"
    fig.savefig(fig_file, dpi=200, bbox_inches="tight")
    plt.close(fig)

    summary = {
        "n_time_points": int(solution.t.size),
        "final_state": solution.y[:, -1].tolist(),
        "config": str(config_path),
        "npz": str(npz_file),
        "figure": str(fig_file),
    }
    summary_file = output_path / "smoke_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")

    return SmokeArtifacts(npz_path=npz_file, figure_path=fig_file, summary_path=summary_file)
